app = "packs-frontend"
primary_region = "ewr"

[build]

[env]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[http_service.checks]]
  interval = "15s"
  grace_period = "10s"
  method = "GET"
  path = "/"
  protocol = "http"
  timeout = "5s"
  tls_skip_verify = false

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256 