app = "packs-backend"
primary_region = "ewr"

[build]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  interval = "10s"
  grace_period = "5s"
  method = "GET"
  path = "/api/v1/health"
  protocol = "http"
  timeout = "2s"
  tls_skip_verify = false

[processes]
  app = "./app"

# [deploy]
#   release_command = "./app migrate"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512 